addSbtPlugin("org.scalameta"       % "sbt-scalafmt"       % "2.5.5")
addSbtPlugin("com.github.sbt"      % "sbt-git"            % "2.1.0")
addSbtPlugin("com.rallyhealth.sbt" % "sbt-git-versioning" % "1.6.0")
addSbtPlugin("com.eed3si9n"        % "sbt-projectmatrix"  % "0.10.1")
addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"       % "3.12.2")
addSbtPlugin("com.github.sbt"      % "sbt-pgp"            % "2.3.1")
