addSbtPlugin("org.scalameta"       % "sbt-scalafmt"       % "2.5.1")
addSbtPlugin("com.github.sbt"      % "sbt-git"            % "2.0.1")
addSbtPlugin("com.rallyhealth.sbt" % "sbt-git-versioning" % "1.6.0")
addSbtPlugin("com.eed3si9n"        % "sbt-projectmatrix"  % "0.9.1")
addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"       % "3.9.21")
addSbtPlugin("com.github.sbt"      % "sbt-pgp"            % "2.2.1")
